docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - if [ "$PRERENDER" = "true" ]; then docker build --pull --build-arg $(tr '\n' ' ' < .env | sed "s/ / --build-arg /g") --build-arg PRERENDER=true -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:full" .; fi;
    - if [ "$PRERENDER" = "true" ]; then docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:full"; fi;
    - if [ "$PRERENDER" = "true" ]; then exit 0; fi;
    - docker build --pull --build-arg $(tr '\n' ' ' < .env | sed "s/ / --build-arg /g") -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest"
    - docker build --pull --build-arg $(tr '\n' ' ' < .env | sed "s/ / --build-arg /g") -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
pages:
  image: node:18
  stage: deploy
  script:
    - yarn install
    - yarn build
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
stages:
  - build
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup
sast:
  stage: test
include:
  - template: Auto-DevOps.gitlab-ci.yml

